// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CodeSessionStatus string

const (
	CodeSessionStatusActive   CodeSessionStatus = "active"
	CodeSessionStatusInactive CodeSessionStatus = "inactive"
)

func (e *CodeSessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CodeSessionStatus(s)
	case string:
		*e = CodeSessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CodeSessionStatus: %T", src)
	}
	return nil
}

type NullCodeSessionStatus struct {
	CodeSessionStatus CodeSessionStatus
	Valid             bool // Valid is true if CodeSessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCodeSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CodeSessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CodeSessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCodeSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CodeSessionStatus), nil
}

type ExecutionStatus string

const (
	ExecutionStatusQueued    ExecutionStatus = "queued"
	ExecutionStatusRunning   ExecutionStatus = "running"
	ExecutionStatusCompleted ExecutionStatus = "completed"
	ExecutionStatusFailed    ExecutionStatus = "failed"
	ExecutionStatusTimeout   ExecutionStatus = "timeout"
)

func (e *ExecutionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExecutionStatus(s)
	case string:
		*e = ExecutionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ExecutionStatus: %T", src)
	}
	return nil
}

type NullExecutionStatus struct {
	ExecutionStatus ExecutionStatus
	Valid           bool // Valid is true if ExecutionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExecutionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ExecutionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExecutionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExecutionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExecutionStatus), nil
}

type Language string

const (
	LanguagePython Language = "python"
	LanguageGo     Language = "go"
)

func (e *Language) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Language(s)
	case string:
		*e = Language(s)
	default:
		return fmt.Errorf("unsupported scan type for Language: %T", src)
	}
	return nil
}

type NullLanguage struct {
	Language Language
	Valid    bool // Valid is true if Language is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLanguage) Scan(value interface{}) error {
	if value == nil {
		ns.Language, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Language.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLanguage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Language), nil
}

type CodeSession struct {
	ID         uuid.UUID
	Status     CodeSessionStatus
	Language   Language
	SourceCode string
}

type Execution struct {
	ID              uuid.UUID
	Status          ExecutionStatus
	Stdout          pgtype.Text
	Stderr          pgtype.Text
	ExecutionTimeMs pgtype.Int2
}

type ExecutionLog struct {
	ID          int64
	ExecutionID uuid.UUID
	Status      ExecutionStatus
	Timestamp   pgtype.Timestamp
}
